### ISSUE TITLE
How to simulate custom cloth in ARGUS?

### ISSUE THREAD

**Issue by wxhaooo** [lijieumn/argus-distribution#8]
ARGUS is an impressive thin-shell simulator but I suffer some difficulties when I try to simulate custom cloth in ARGUS. Concretely, I can not achieve stitched cloth when I simulate custom garment making with Houdini following `README.md` of arcsim [arcsim in githhub](https://github.com/wxntech/arcsim). Unfortunately, I can not get planned results even I merge parametrization space and world space mesh! Would you give me more guide to simulate custom garment? I'll appreciate your help!

**Comment by narain** [comment]
Can you share the meshes you are trying to simulate with, and explain in more detail what problems you encounter?

**Comment by wxhaooo** [comment]
Thanks for your replay. Fortunately, I solve the problem yesterday. The reason arose the problem is the simulator requires garments that form manifolds with consistent orientation. Thank you very much for your help!
